#include "orbsvcs/TimeBase.idl"

module DDSTopic
{
#pragma DCPS_DATA_TYPE "DDSTopic::msg"
#pragma DCPS_DATA_KEY "DDSTopic::msg sender"
  struct msg
  {
    string sender;
    string data;
    long type;
  };
  const string msgTypeName = "Message_t";
};
